# -*- coding: utf-8 -*-
"""NMN pain-point -> creative brief matrix. Single source for xlsx + html."""

ROWS = [
# ---------------- PSYCHOLOGICAL / IDENTITY ----------------
dict(n=1, persona="Linda", cat="Psychological / identity", tier="Proven", funnel="Cold",
 pain="“I’m becoming invisible.”",
 surface="“I’m tired all the time.”",
 deep="She used to run everything — the household, the holidays, the job. Now she sits while others do. Her body is betraying the person she still believes she is.",
 evidence="‘More energy’ is the #1 ManyChat tag. ‘Tired in a way sleep doesn’t fix’ is the #1 landing-page hook.",
 fmt="UGC testimonial",
 angle="Identity reclamation — not “get energy”, but “get you back”",
 hook="Tired of sitting out the things you used to run?",
 heading="You’re still in there.",
 subheading="It’s not just aging — your NAD+ is collapsing. Rebuild it and get your days back.",
 idea="The pain isn’t fatigue, it’s watching yourself become a spectator in your own house. Open on the moment of sitting down while everyone else keeps moving. Qualifies hard — anyone who hasn’t felt this scrolls straight past.",
 poster="Warm domestic interior, late afternoon. Woman ~62 seated in an armchair, mid-ground, slightly soft focus. Behind her, sharp focus: family in motion — someone carrying dishes, a child running past. She is watching, not participating. Plain serif type across the upper third: “When did you become the one who watches?” Bottom bar: product + “$29.98 → $16.66”. No smiling, no stock-photo energy.",
 reel="20s vertical, captions burned in. 0–3s: locked shot, she lowers herself into the chair as family noise continues off-frame. VO: “Tired of sitting out the things you used to run?” 3–9s: quick cuts of what she’s stopped doing — car keys left on the hook, garden gloves unused, a call declined. VO names the mechanism: “It’s not just aging. Your NAD+ is collapsing.” 9–15s: capsule taken with morning coffee; VO: “Rebuild it and get back clean energy, sharp focus and clear thinking.” 15–20s: same chair, same light — empty, and we hear her outside. End card: bottle, per-bottle price, “See how it works →”. No music until 15s."),

dict(n=2, persona="Linda", cat="Psychological / identity", tier="Proven", funnel="Cold",
 pain="“Am I losing my mind?”",
 surface="“Brain fog, I can’t focus.”",
 deep="She watched her mother or aunt go through dementia. Every forgotten word triggers a cold wave of fear about becoming a burden to her children.",
 evidence="NMN_Focus is a self-identified ManyChat tag. Cognitive decline is named the most visceral fear for 55+.",
 fmt="Talking-head direct address",
 angle="Name the fear precisely, then give it a mechanism that isn’t dementia",
 hook="Forgot another name this week?",
 heading="It’s probably not what you’re afraid of.",
 subheading="Your brain burns more NAD+ than any organ you have. Yours is running out.",
 idea="She is silently terrified and most brands won’t say the word, so she stays scared. Say the fear out loud, then offer a smaller, fixable explanation. Enormous relief converts to enormous intent.",
 poster="Tight portrait, woman ~63, neutral expression, direct eye contact, plain background, soft window light from the left. Large type across the lower third: “Forgot another name this week?” Smaller second line: “It’s probably not what you’re afraid of.” Deliberately un-styled — no props, no product hero. Product appears small, bottom-right.",
 reel="20s. 0–3s: her face, direct to camera, silence, then: “I forgot my own grandson’s name at his birthday.” 3–8s: still on face — “I sat in the car afterwards and cried, because I thought this is how it started with my mother.” 8–14s: cut to a simple animated mechanism card — brain, NAD+ level falling. Second VO, calmer, expert: “Your brain consumes more NAD+ than any organ in your body. After 50, levels collapse.” 14–18s: back to her, lighter: “It’s been three months. I haven’t blanked once.” 18–20s: end card, “Learn the mechanism →”. No music. Handheld, imperfect."),

dict(n=3, persona="Linda", cat="Psychological / identity", tier="Adjacent", funnel="Warm (Day 21)",
 pain="“I look older than I feel inside.”",
 surface="“Fine lines, dull skin, visible aging.”",
 deep="She catches her reflection and the person she sees doesn’t match the person she feels like. This is an identity crisis, not vanity.",
 evidence="‘Look 10 years younger’ framing on the product page. She buys NMN for energy, then adds ASTA for the mirror.",
 fmt="Before/after",
 angle="The mirror is lying",
 hook="The woman in the mirror isn’t the one you feel like.",
 heading="Your face is aging faster than you are.",
 subheading="Cellular energy shows up in your skin first. Rebuild it from the inside.",
 idea="This is the ASTA attach point, but framed through NMN’s mechanism so it strengthens the core product instead of competing with it. Runs to existing customers at Day 21 — never cold, which is how ASTA is currently mispositioned.",
 poster="Split vertical. Left: a mirror reflection, cool blue-grey cast, slightly desaturated. Right: the same woman turned away from the mirror, warm golden light, alive. Vertical type between the panels: “Same woman. Two different ages.” Bottom: NMN + ASTA pair shot with combined per-bottle math.",
 reel="20s. 0–3s: a hand wipes condensation from a bathroom mirror, face appears. VO: “The woman in the mirror isn’t the one you feel like.” 3–8s: she leans in, examines under her eyes and jaw — unflinching, no shame framing. 8–13s: mechanism card — cellular energy shows up in skin before anywhere else. 13–18s: same mirror, different day, better light; she doesn’t linger, she just goes. 18–20s: NMN + ASTA end card, “See the pairing →”."),

dict(n=4, persona="Linda", cat="Psychological / identity", tier="Adjacent", funnel="Cold",
 pain="“I can’t keep up with my grandchildren.”",
 surface="“Low energy, slow recovery.”",
 deep="Her grandchildren are the most important people in her life. When she can’t get on the floor and play, she is failing at the most important role she has left. This is about purpose, not fitness.",
 evidence="Grandchildren named as the most important people in her life; longevity/family ManyChat tag.",
 fmt="Emotive story",
 angle="Purpose loss, not physical loss",
 hook="When did getting down on the floor become the hard part?",
 heading="Getting down isn’t the problem. Getting up is.",
 subheading="It’s not just aging — your NAD+ is collapsing. Rebuild it and be the grandmother you planned on.",
 idea="The specific, undignified detail — needing to brace to stand — does more work than any general energy claim. Highly qualifying: only someone who has lived that exact moment reacts to it.",
 poster="Low camera angle at a child’s eye level, looking up. Woman ~62 on the floor mid-play, one hand braced on the carpet — the brace is the whole story. Natural living-room light, toys scattered, genuinely untidy. Type upper left: “Getting down isn’t the problem.” Smaller beneath: “Getting up is.” Product small, bottom-right.",
 reel="20s. 0–3s: floor-level shot, a 3-year-old’s hands building blocks; a grandmother’s hand enters frame, then the sound of her bracing to stand. VO: “When did getting down on the floor become the hard part?” 3–9s: she sits on the edge of the sofa instead, watching. VO names the mechanism. 9–15s: brief, plain shots of the capsule in a morning routine. 15–19s: same floor, same child — she gets up without the brace and lifts him. 19–20s: end card. Music enters only at 15s."),

dict(n=5, persona="Linda", cat="Psychological / identity", tier="Adjacent", funnel="Cold",
 pain="“My body stopped listening to me.”",
 surface="“Post-menopause fatigue, weight that won’t budge, hormonal crashes.”",
 deep="For decades her body was predictable. Now it does things she doesn’t understand and her doctor says it’s normal. Normal doesn’t make it less terrifying. She doesn’t want to accept aging — she wants her body back.",
 evidence="Post-menopause fatigue is a Tier 2 pain point. Women 55–64 are the second-largest spending segment ($43K in 90 days).",
 fmt="Talking-head direct address",
 angle="Validate against medical dismissal",
 hook="Your doctor said it’s normal. Normal isn’t the same as fine.",
 heading="You’re not imagining it.",
 subheading="There’s a name for what’s happening, and it isn’t “your age”.",
 idea="She has been dismissed by a professional. Being believed is the conversion event. Highest-empathy hook in the set and it qualifies cleanly — only someone who has been brushed off responds to it.",
 poster="Woman ~60 seated on exam-table paper, clinical setting, fully dressed, waiting. Flat overhead fluorescent light, deliberately unflattering. Large type across the middle: “It’s normal for your age.” Struck through. Beneath: “Normal isn’t the same as fine.” Product in the bottom bar only.",
 reel="20s. 0–3s: exam room, paper crinkling, off-screen voice: “That’s normal at your age.” Cut to her face, no reaction. VO: “Your doctor said it’s normal.” 3–8s: “Normal isn’t the same as fine.” Quick honest cuts — 3pm on the clock, standing up too slowly, staring into a fridge. 8–14s: expert VO over a simple mechanism card, NAD+ decline after 50 in women. 14–18s: her, at home, plainly: “I stopped accepting it.” 18–20s: end card, “Learn what’s actually happening →”."),

dict(n=6, persona="Linda", cat="Psychological / identity", tier="Adjacent", funnel="Cold",
 pain="“My husband doesn’t understand.”",
 surface="“I don’t feel like myself.”",
 deep="She can’t articulate the fatigue, the fog, the appearance anxiety to her husband. He sees her as fine. She is fine — from the outside. She wants something to validate that what she’s experiencing is real and fixable.",
 evidence="Repeat customers are 96% female — she buys this for herself, not as a gift. ‘It’s not just aging’ is named as the validation line.",
 fmt="Talking-head direct address",
 angle="Private validation",
 hook="He says you look fine. He’s not the one living in there.",
 heading="You’re not imagining it.",
 subheading="It’s not just aging — your NAD+ is collapsing. There’s a name for it.",
 idea="She is fighting a daily battle nobody else can see. The ad’s job is to be the first thing that says this is real. Note: she buys for herself — never frame this as a gift or a husband-buys-for-wife concept.",
 poster="Two people on a sofa watching TV, shot from behind. He is relaxed. She is upright, phone in hand, not watching. Type: “He says you look fine.” Second line: “He’s not the one living in there.” Product bottom bar.",
 reel="20s. 0–4s: woman ~60, direct to camera, kitchen: “My husband says I look great.” 4–9s: “He doesn’t know I sat in the car for ten minutes before coming in, because I didn’t have it in me yet.” 9–14s: mechanism, calm expert VO. 14–19s: her again, lighter, unforced. 19–20s: end card. Filmed plainly, no styling — in this account the winners are plain and the losers are polished."),

dict(n=7, persona="Linda", cat="Psychological / identity", tier="Adjacent", funnel="Cold",
 pain="“I’m falling behind my friends.”",
 surface="“My friend has more energy than me.”",
 deep="She is in a social circle of women her age who walk, lunch, volunteer together. When one seems to have more vitality it creates a quiet, corrosive comparison. She doesn’t want to be the tired one.",
 evidence="Social proof works because she imagines being the woman who says ‘I feel 10 years younger’. 5,128 reviews, 500K+ customers.",
 fmt="UGC comparison",
 angle="Peer-group comparison — reclaiming former status, not chasing a new one",
 hook="She’s 64 and finishes the walk. You used to be her.",
 heading="You used to be the one setting the pace.",
 subheading="It’s not just aging — your NAD+ is collapsing. Rebuild it.",
 idea="Envy is uncomfortable but extremely reliable in this cohort. Do not shame her — position her as someone reclaiming a status she already held, which is dignified rather than aspirational.",
 poster="Three women in their 60s on a neighbourhood walking path, Sun Belt morning light, palms or desert planting visible. Two ahead mid-conversation; one half a pace behind, looking at the gap. Shot from behind so no faces are visible — she projects herself in. Type: “You used to be the one setting the pace.” Product bottom bar.",
 reel="20s. 0–3s: walking-path POV, two friends pulling ahead. VO: “She’s 64 and she finishes the walk.” 3–8s: “You used to be her.” Cut to her stopping to catch her breath, pretending to check her phone — the specific, humiliating detail. 8–14s: mechanism and capsule. 14–19s: same path, she’s level with them, mid-laugh, not looking at camera. 19–20s: end card. Real ambient sound — birds, footsteps, breathing."),

dict(n=8, persona="Linda", cat="Psychological / identity", tier="Adjacent", funnel="Cold",
 pain="“I’m running out of time.”",
 surface="“Longevity, healthy aging.”",
 deep="She’s past the midpoint and knows it. Every year matters more. Every day she feels tired is a day she can’t get back. NMN isn’t a supplement to her — it’s a time machine.",
 evidence="NMN_Longevity is the third ManyChat tag. Positioned as cellular energy, but the deeper positioning is youth recovery.",
 fmt="Emotive story",
 angle="Time scarcity, framed as presence rather than mortality",
 hook="Every tired year is a year you don’t get back.",
 heading="You don’t get these years twice.",
 subheading="Your NAD+ is collapsing. Rebuild it while the years still count.",
 idea="The most emotionally loaded angle in the set — handle without melodrama. No death imagery, no violins. The frame is presence, not mortality; restraint is what makes it land.",
 poster="A grandmother and a small child on a porch in late golden light, both looking out, not at camera. Composition leaves large negative space to the right. Quiet, small type in that space: “He’ll remember whether you were there. Or whether you were tired.” Product small, bottom-right. Deliberately restrained.",
 reel="20s. 0–3s: hand-held phone video of a child’s birthday, shaky and real. Plain VO: “Every tired year is a year you don’t get back.” 3–9s: still frames from family photos months apart, the same woman visibly less present in each. 9–14s: mechanism, brief and unsentimental. 14–19s: new footage — she’s in the frame rather than behind the camera. 19–20s: end card, “See how it works →”."),

# ---------------- PHYSIOLOGICAL / SYMPTOM ----------------
dict(n=9, persona="Linda", cat="Physiological / symptom", tier="Proven", funnel="Cold",
 pain="“I sleep eight hours and wake up like it was four.”",
 surface="“I’m tired even after a full night.”",
 deep="This is the one symptom that proves to her it isn’t simply ‘not enough sleep’ — it’s something structural. It is the reason she is willing to believe a cellular explanation.",
 evidence="Named the #1 landing-page hook. Part 6: ‘she wakes up feeling like she slept 4 hours even though she slept 8’.",
 fmt="Problem/solution split",
 angle="The disqualifying symptom — the most self-identifying line you own",
 hook="Slept eight hours. Woke up like it was four.",
 heading="Sleep isn’t the problem.",
 subheading="It’s not just aging — your NAD+ is collapsing. That’s why rest doesn’t fix it.",
 idea="The single most specific, most self-identifying symptom in the entire research. A perfect qualifier: people without it don’t recognise it at all, people with it feel seen instantly. This should be your highest-volume production angle.",
 poster="Bedside table at 6:30 AM. Phone face-up showing the time, a glass of water, reading glasses. Sheets thrown back. No person in frame. Cool early light. Type across the top: “8 hours. Woke up like it was 4.” Beneath, smaller: “Sleep isn’t the problem.” Product bottom bar with per-bottle math.",
 reel="20s. 0–3s: alarm sounds, a hand kills it, she doesn’t move. VO: “Slept eight hours. Woke up like it was four.” 3–8s: sitting on the edge of the bed, not standing yet — hold on this uncomfortably long. VO: “It’s not just aging. Your NAD+ is collapsing — that’s why rest doesn’t fix it.” 8–14s: clean mechanism card, four seconds maximum. 14–19s: a different morning, she’s up and out the door in one continuous shot. 19–20s: end card."),

dict(n=10, persona="Linda", cat="Physiological / symptom", tier="Proven", funnel="Cold",
 pain="“The 3 o’clock crash.”",
 surface="“My energy collapses every afternoon.”",
 deep="A predictable daily humiliation. She plans her life around it — appointments in the morning, nothing after two.",
 evidence="Explicit landing-page hook. 2–5 PM runs 229–252 orders/hour — she is living the pain point at the moment she sees the ad.",
 fmt="Problem/solution split",
 angle="Real-time symptom targeting",
 hook="It’s 3 PM. You already know how this goes.",
 heading="The crash isn’t a habit. It’s a fuel problem.",
 subheading="Rebuild your NAD+ and stop scheduling your life around three o’clock.",
 idea="Serve this ad specifically between 2–5 PM ET. She is living the pain as she reads it, and the research shows she orders in exactly this window. This is the highest-leverage dayparting play available to you.",
 poster="A kitchen clock reading 3:05, sharp in the foreground. Background soft: a woman sitting down at a table, head propped on her hand. Warm but flat afternoon light. Type: “It’s 3 PM. You already know how this goes.” Product bottom bar.",
 reel="20s. 0–3s: hard cut to a clock at 3:00, then her sitting down mid-task. VO: “It’s three o’clock. You already know how this goes.” 3–8s: montage of coping mechanisms — the second coffee, sitting in the parked car, “I’ll do it tomorrow”. 8–13s: mechanism: “This isn’t willpower. It’s NAD+.” 13–18s: 3 PM again, she keeps going — same clock, different outcome. 18–20s: end card. SCHEDULING: deliver 2–5 PM ET."),

dict(n=11, persona="Linda", cat="Physiological / symptom", tier="Untested", funnel="Cold",
 pain="“Exhausted all day, wide awake at midnight.”",
 surface="“I can’t sleep.”",
 deep="The exhaustion loop — too tired to function, too wired to rest. She is demonstrably awake and shopping at midnight.",
 evidence="205 orders at 12 AM; 127–206 orders/hour between 11 PM and 1 AM. The report flags overnight activity as a sleep-issue signal and sleep support as a Tier 1 product opportunity.",
 fmt="Talking-head direct address",
 angle="The tired-but-wired loop",
 hook="Exhausted all day. Wide awake at midnight.",
 heading="Tired and wired is a real thing.",
 subheading="Your cells run on a clock too — and yours has lost the signal.",
 idea="She is provably awake and buying at midnight and nobody is talking to her at that hour. Untested as an angle, but the behavioural evidence is unusually direct. Serve 10 PM–1 AM ET.",
 poster="Dark bedroom, the only light a phone screen illuminating a face from below. Clock visible reading 12:47. Type: “Exhausted all day. Wide awake at midnight.” Restrained — no product hero, product in a small bottom bar.",
 reel="20s, shot almost entirely in low light. 0–3s: ceiling, from her point of view in bed. Quiet close-mic VO: “Exhausted all day. Wide awake at midnight.” 3–9s: the loop — phone check, clock check, sigh, phone check. 9–14s: mechanism, cellular clock, dim-friendly graphics. 14–19s: morning, curtains open, she’s up without the struggle. 19–20s: end card. SCHEDULING: deliver 10 PM–1 AM ET."),

dict(n=12, persona="Linda", cat="Physiological / symptom", tier="Untested", funnel="Cold",
 pain="“One good day costs me the next two.”",
 surface="“I recover slowly now.”",
 deep="Her capacity has a ceiling and she is constantly negotiating with it. She isn’t doing less — she’s paying more for the same.",
 evidence="Active Sun Belt lifestyle — walking, gardening, swimming, golf — combined with the low-energy / slow-recovery pain point.",
 fmt="UGC testimonial",
 angle="The recovery tax",
 hook="One good day still costs you the next two.",
 heading="You’re not doing less. You’re paying more for it.",
 subheading="Rebuild your NAD+ and stop budgeting your week around one afternoon.",
 idea="Reframes the problem from “I’m tired” to “I’m rationing” — a more precise and more painful description she will recognise instantly. Strong for the active Sun Belt segment.",
 poster="A garden half-finished — tools down, a bag of soil open, gloves on the step. Bright Arizona light, hard shadows. Nobody in frame. Type: “One good day still costs you the next two.” Product bottom bar.",
 reel="20s. 0–4s: she is gardening, genuinely working, real effort and sweat. VO: “Saturday, I did the whole yard.” 4–9s: hard cut to Sunday — curtains closed, still in a robe at 11 AM: “Sunday I couldn’t move. Monday either.” 9–14s: mechanism, short. 14–19s: Saturday gardening again, then Sunday — dressed, out, keys in hand. 19–20s: end card."),

dict(n=13, persona="Linda", cat="Physiological / symptom", tier="Adjacent", funnel="Cold",
 pain="“I lose the word mid-sentence and everyone waits.”",
 surface="“I can’t find words like I used to.”",
 deep="Public, witnessed cognitive failure — materially worse than private forgetting. The silence while people wait is the specific horror.",
 evidence="‘Every time she forgets a word or blanks on a name, a cold wave of fear hits.’ Cognitive decline is the most visceral 55+ fear.",
 fmt="UGC testimonial",
 angle="The witnessed moment",
 hook="You lost the word again. And everyone waited.",
 heading="The pause is the part that scares you.",
 subheading="Your brain runs on NAD+. Rebuild it and stop losing the thread.",
 idea="Distinct from row 2 — that one is private dread, this is social humiliation. Build the whole ad around three seconds of real silence at a dinner table. Very high recognition.",
 poster="A dinner table shot from her seat — three friends mid-conversation, all looking toward camera, waiting. Slight motion blur on them, sharp focus on the empty place setting. Type: “And then everyone waited.” Product bottom bar.",
 reel="20s. 0–5s: dinner table, she’s mid-story, then stops. Real silence — hold it for three uncomfortable seconds while friends wait. 5–9s: VO: “You lost the word again. And everyone waited.” 9–14s: mechanism card. 14–19s: same table, the story lands, laughter. 19–20s: end card. The three-second silence is the entire ad — do not let an editor trim it."),

dict(n=14, persona="Linda", cat="Physiological / symptom", tier="Untested", funnel="Cold",
 pain="“Same food, same walk, different body.”",
 surface="“The weight won’t move.”",
 deep="The rules she lived by for forty years stopped working, with no explanation and no warning.",
 evidence="Post-menopause weight gain named as a core insecurity; weight management flagged as a Tier 3 product opportunity.",
 fmt="Talking-head direct address",
 angle="The rules changed without telling her — metabolic energy, NOT weight loss",
 hook="Same food. Same walk. Different body.",
 heading="You didn’t change. The engine did.",
 subheading="Your cells burn fuel differently after 50. That starts with NAD+.",
 idea="Do NOT position NMN as a weight-loss product — it isn’t one and the claim risk is real. Position it as metabolic energy and let her draw her own connection. COMPLIANCE: legal review before this runs.",
 poster="A closet with one pair of trousers hung apart from the rest, tag still on. Domestic, honest, no bodies in frame — avoids body-shaming imagery entirely. Type: “Same food. Same walk. Different body.” Product bottom bar.",
 reel="20s. No body shots, no scales, no physique before/after — the ad is about energy, not size. 0–4s: woman ~60 at a kitchen counter, plainly: “I eat what I’ve always eaten. I walk what I’ve always walked.” 4–9s: “Nothing works the way it used to.” 9–14s: mechanism — cellular fuel, not fat loss; keep claims tight. 14–19s: out walking, energetic, fully clothed, filmed from a respectful distance. 19–20s: end card. COMPLIANCE: no weight-loss claims anywhere in copy or captions."),

dict(n=15, persona="Linda", cat="Physiological / symptom", tier="Untested", funnel="Warm (bundle attach)",
 pain="“Stiffness is taking the things I moved here to do.”",
 surface="“My joints hurt.”",
 deep="Mobility loss is the thing that will end her independent outdoor life. She moved somewhere warm for that life; losing it makes the move pointless.",
 evidence="‘She’s active — walking, gardening, swimming. Joint pain is the #1 limiter for 60+ active adults.’ Joint support is a Tier 2 opportunity.",
 fmt="Carousel",
 angle="Protect the lifestyle she relocated for",
 hook="You moved somewhere warm so you could stay outside.",
 heading="Don’t let stiffness take the reason you moved.",
 subheading="Energy inside, mobility outside — the pairing for an active 60s.",
 idea="This is the natural home for Multi Collagen, a SKU far too small to fund its own cold traffic. Sells the NMN + Collagen pair, never Collagen alone. BLOCKER: Collagen COGS is null — fix before promoting.",
 poster="Card 1: a pool at 7 AM, Sun Belt, empty lane, long shadows. Type: “You moved somewhere warm so you could stay outside.” Card 2: the pairing shot, NMN + Collagen, with combined per-bottle math. Card 3: a plain benefit list — no icons, no gradients.",
 reel="20s. 0–4s: desert morning, someone walking a dog past saguaro or palms. VO: “You moved somewhere warm so you could stay outside.” 4–9s: the compromises — the shorter loop, the handrail, sitting down to put shoes on. 9–14s: the pairing explained simply, inside and outside. 14–19s: the longer loop, taken. 19–20s: pair end card. Warm/retention audiences only."),

# ---------------- COMPARATIVE / TRUST ----------------
dict(n=16, persona="Linda", cat="Comparative / trust", tier="Proven", funnel="Cold",
 pain="“I’ve been scammed before.”",
 surface="“Supplements are a scam.”",
 deep="She’s tried collagen, CoQ10, turmeric. Most did nothing. She spent money she shouldn’t have and is ashamed of how gullible she was. Now she reads every word looking for a reason NOT to buy.",
 evidence="The 5,128 reviews, Forbes/ELLE mentions and the ‘64% of NMN products fail lab tests’ claim all work because they validate her distrust while positioning you as the exception.",
 fmt="Product demo + COA",
 angle="Category-quality contrast — validate her distrust, then be the exception",
 hook="Not all NMN is created equal — and 64% of them fail lab tests.",
 heading="You were right to be suspicious.",
 subheading="Most NMN on the shelf is underdosed or degraded. Here’s our third-party lab report.",
 idea="“Not all X is created equal” produced 3 of your 12 all-time winners at the best CPM in the account ($57.47 vs $98.37) — but has only ever run on Astaxanthin, ~4% of revenue. Never on NMN, which is 94%. This is the single highest-expected-value untested creative you can brief.",
 poster="Split frame. Left: three unbranded generic supplement bottles, desaturated, grey-cast, slightly blurred. Right: the NMN Complex bottle, sharp, warm key light, on clean white with an actual COA sheet partly visible beneath. Bold type across the top third: “64% FAIL LAB TESTS.” Bottom bar carries the per-bottle anchor “$29.98 → $16.66” — no percentage. Cool grey versus warm neutral. No lifestyle imagery, no model.",
 reel="20s, vertical, captions burned in. 0–3s: hands set three generic bottles on a kitchen counter. VO: “Not all NMN is created equal.” 3–8s: a real lab report scrolls on a phone screen, a finger tracking a highlighted failure line — “64% of them fail third-party testing.” 8–14s: cut to our bottle, slow rotate, on-screen text stamps actual mg dosage and purity. 14–18s: a woman in her 60s, plainly dressed, kitchen, no styling: “I’ve wasted a lot of money on supplements. I checked this one before I bought it.” 18–20s: bottle, per-bottle price, “See the lab report →”. No music bed under the VO — ambient kitchen sound only."),

dict(n=17, persona="Linda", cat="Comparative / trust", tier="Adjacent", funnel="Cold",
 pain="“Why is yours more expensive than the one on Amazon?”",
 surface="“I found NMN for $18.”",
 deep="Price is a proxy for ‘am I being taken advantage of again’. The objection is about trust, not budget.",
 evidence="‘64% of NMN products fail lab tests’. The bundle is described as a trust signal disguised as a discount.",
 fmt="Product demo + COA",
 angle="Price per actual dose, not price per bottle",
 hook="The cheap one isn’t cheaper. It’s just less.",
 heading="$18 for half the dose isn’t a saving.",
 subheading="Compare the mg, not the price tag. Then compare ours — $16.66 a bottle.",
 idea="Turns her price objection into a quality qualifier, and crucially lets you lead with the per-bottle anchor honestly without ever using a discount headline. Do not name or show a real competitor brand.",
 poster="Two bottles side by side, photographed identically on clinical white. Overlaid on each: actual mg per serving, servings per bottle, cost per effective dose — three lines of real arithmetic each. Type above: “The cheap one isn’t cheaper. It’s just less.” Generic/unbranded comparison bottle only.",
 reel="20s. 0–4s: two bottles on a counter. VO: “This one’s eighteen dollars. This one’s more.” 4–10s: hands turn both to the supplement facts panel; on-screen math builds line by line — mg, servings, cost per dose. 10–15s: “The cheap one isn’t cheaper. It’s just less.” 15–19s: our bottle alone, per-bottle price stamped. 19–20s: “See the numbers →”. No music, counter-top ambient only."),

dict(n=18, persona="Linda", cat="Comparative / trust", tier="Adjacent", funnel="Cold",
 pain="“I’ve tried collagen, CoQ10, turmeric — none of it worked.”",
 surface="“Supplements don’t work on me.”",
 deep="Accumulated evidence of her own gullibility. Every failed bottle is a small private humiliation sitting in her cabinet.",
 evidence="‘She’s tried things. Probably collagen, probably CoQ10, probably turmeric. Some worked a little. Most didn’t.’",
 fmt="Founder/expert explainer",
 angle="Why the others failed — a mechanism she can check",
 hook="Collagen. CoQ10. Turmeric. None of them touched the actual problem.",
 heading="They weren’t scams. They were the wrong target.",
 subheading="None of them raise NAD+. That’s the one that runs your cells.",
 idea="Rather than claiming to be better, explain why the category she already tried was aimed elsewhere. Gives her a face-saving reason her past purchases failed — she wasn’t stupid, she was misdirected. Removes shame, which removes resistance.",
 poster="A bathroom cabinet shelf, honestly cluttered with half-used supplement bottles, labels turned away. One clean space at the front. Type: “They weren’t scams. They were the wrong target.” Product placed in the clean space.",
 reel="20s. 0–4s: hands take bottles off a shelf one at a time, naming them — collagen, CoQ10, turmeric — setting each aside. 4–10s: expert to camera, plainly dressed, no lab coat: “Every one of those targets something downstream. None of them raise NAD+.” 10–15s: a single clean mechanism graphic. 15–19s: our bottle set into the cleared space. 19–20s: “Understand the difference →”."),

dict(n=19, persona="Linda", cat="Comparative / trust", tier="Untested", funnel="Cold",
 pain="“I don’t understand NMN versus NR versus NAD+ drips.”",
 surface="“There are too many versions of this.”",
 deep="Confusion is a reason to postpone. She won’t buy something she can’t explain to her husband or her friend.",
 evidence="Category education gap; the product page leads on mechanism. Google/Threads convert at 5.08% — the highest of any source — which is search intent from people trying to understand the category.",
 fmt="Founder/expert explainer",
 angle="Make her the informed one",
 hook="NMN, NR, NAD+ drips — only one of these is worth your money.",
 heading="Three names. One that matters.",
 subheading="Here’s the difference in thirty seconds, so you can stop guessing.",
 idea="Confusion is a silent conversion killer in this category. An ad that resolves it earns disproportionate trust, and she will repeat the explanation to a friend — which is how this audience actually spreads. Also the natural creative to pair with the untapped search channel.",
 poster="A plain three-column comparison, typographic, almost no imagery — NMN / NR / IV drips, one honest line each on how it works, cost, and evidence. Deliberately unglamorous, like a printed handout from a doctor’s office. Small product mark at the base.",
 reel="20s, whiteboard or plain-card explainer. 0–3s: “NMN, NR, NAD+ drips. Only one of these is worth your money.” 3–14s: three cards, roughly 3.5s each, one honest sentence per option — including a fair word about the others, which is what makes it credible. 14–19s: “NMN is the one your cells can actually use, and the only one you can take at home.” 19–20s: end card. No music, no motion-graphics flourish — it must feel like information, not advertising."),

dict(n=20, persona="Linda", cat="Comparative / trust", tier="Untested", funnel="Retention (Day 12)",
 pain="“How do I know it’s even working?”",
 surface="“I can’t tell if it’s doing anything.”",
 deep="She has no visible marker to prove to herself the money wasn’t wasted — which is the same fear as row 16, arriving after the purchase instead of before it.",
 evidence="The scam insecurity combined with the churn risk: the business breaks even at 0.59 re-bills per subscriber, so a customer quitting at day 10 is a direct loss.",
 fmt="Static offer card",
 angle="Give her a measurable milestone",
 hook="Day 14 is when most women notice. Here’s exactly what to look for.",
 heading="You’ll know it’s working when 3 PM stops happening.",
 subheading="Most women notice between day 12 and day 21. Mark the date.",
 idea="This is churn insurance, not acquisition. Telling her when to expect results is the single cheapest thing you can do to protect the 0.59 re-bills breakeven, because it stops her quitting at day 10. Send by email at Day 12 — do not run as paid cold traffic.",
 poster="A simple calendar page, days 1–21, with day 14 circled by hand in pen. Domestic surface, kitchen counter. Type: “Day 14 is when most women notice.” Below, three specific things to watch for, as a short plain list. Very restrained.",
 reel="20s, or ship as a static in email/SMS. 0–4s: a hand circles day 14 on a wall calendar. VO: “Most women notice between day twelve and day twenty-one.” 4–14s: three concrete markers, ~3s each — waking before the alarm, getting through 3 PM, finishing the sentence. 14–19s: “If you’re on day 8 and nothing’s changed yet, that’s normal. Keep going.” 19–20s: end card. DELIVERY: Day 12 email flow only."),

# ---------------- DEMOGRAPHIC / SITUATIONAL ----------------
dict(n=21, persona="Linda", cat="Demographic / situational", tier="Proven", funnel="Cold",
 pain="“Every dollar is budgeted.”",
 surface="“$30 a bottle is a lot.”",
 deep="She’s on or near a fixed income. If it doesn’t work, that’s not $58 lost — it’s the shame of being fooled again.",
 evidence="‘Social Security + maybe a pension or part-time income... This is why the money-back guarantee is load-bearing.’ Zero discount codes used across 4,770 orders — she responds to the anchor, not to codes.",
 fmt="Static offer card",
 angle="Risk removal, not discount",
 hook="$16.66 a bottle. And if it does nothing, you pay nothing.",
 heading="The math, without the sales pitch.",
 subheading="Six bottles. $16.66 each. Full refund if it doesn’t work for you.",
 idea="The research is explicit that she doesn’t hunt for codes — she responds to per-bottle arithmetic. This is the one place a price-led ad belongs, and it still must never say “75% off”, which lost on conversions-per-click in five months out of five.",
 poster="Pure typographic offer card. Anchor price struck through, per-bottle price large, refund terms in plain readable type — not 8pt legal grey. Warm neutral background. No product beauty shot, no starbursts, no countdown timer. It should look like a receipt, not a promotion.",
 reel="15–20s. 0–4s: bottles placed on a counter one at a time, counted aloud to six. 4–10s: on-screen arithmetic — total, divided, per bottle. 10–16s: “And if it does nothing, you send it back and pay nothing.” 16–20s: end card. No music, no urgency devices. Never use ‘TODAY ONLY’."),

dict(n=22, persona="Linda", cat="Demographic / situational", tier="Untested", funnel="Cold",
 pain="“I moved somewhere warm to be outdoors, and I’m indoors.”",
 surface="N/A — situational",
 deep="She relocated for an active outdoor life. Losing it means the move was pointless, which is a bigger loss than the activity itself.",
 evidence="Arizona is the premium market — Tucson $82 AOV, Phoenix $61, Mesa $52. Retirement-corridor cities across AZ, NV, TX, FL.",
 fmt="UGC testimonial",
 angle="Geo-specific — the life she relocated for",
 hook="You didn’t move to Arizona to spend the afternoon indoors.",
 heading="You moved here for the mornings.",
 subheading="Rebuild your NAD+ and take them back.",
 idea="Produce geo variants for Phoenix, Tucson, Scottsdale, Mesa, Las Vegas and Henderson — the premium-AOV markets. Swap the place name and the establishing shot; everything else holds. Very cheap to produce, unusually specific.",
 poster="Recognisable desert morning — saguaro, low sun, a residential walking path. Woman in her 60s mid-walk, small in frame. Type: “You didn’t move to Arizona to spend the afternoon indoors.” Produce one per city with the place name swapped.",
 reel="20s, one cut per market. 0–4s: local landscape, unmistakable. VO: “You didn’t move to Phoenix to spend the afternoon indoors.” 4–10s: the shrinking world — the walk that got shorter, the pool she doesn’t use, the blinds closing at 2 PM. 10–15s: mechanism. 15–19s: 7 AM, out and moving. 19–20s: end card. Shoot one master and swap the establishing shot and one VO word per city."),

dict(n=23, persona="Linda", cat="Demographic / situational", tier="Proven", funnel="All stages",
 pain="“I don’t want to get trapped in something I can’t cancel.”",
 surface="N/A — situational / friction",
 deep="Checkout friction and subscription anxiety are real for a cohort that has been auto-billed before and struggles to cancel things by phone.",
 evidence="Mobile 103,352 sessions at 4.21%; tablet highest at 5.11%; desktop 1.86%. She checks out with Apple Pay in about four minutes.",
 fmt="Static offer card",
 angle="Frictionlessness as a trust signal",
 hook="Four taps. No account. No subscription trap.",
 heading="Order in under a minute.",
 subheading="Apple Pay, no account needed, cancel any time.",
 idea="Not a pain-point ad but a conversion-rate ad. ‘Subscription trap’ is a genuine fear for this cohort — say the quiet part out loud. COMPLIANCE: verify cancellation is genuinely self-serve before making this claim, and note 97% of orders are now subscriptions so the claim must be exact.",
 poster="A phone held in a hand, screen showing the real checkout with Apple Pay visible. Nothing else in frame. Type: “Four taps. No account.” Use an honest screenshot — do not mock up a fake UI.",
 reel="12–15s screen recording. Real thumb, real device, real flow, unedited timing: select bundle → Apple Pay → done. On-screen timer running in the corner to prove the duration. VO: “Four taps. No account. Cancel any time.” COMPLIANCE: only run if cancellation is genuinely self-serve."),

# ---------------- BEHAVIOURAL / PURCHASE FRICTION ----------------
dict(n=24, persona="Linda", cat="Behavioural / purchase friction", tier="Proven", funnel="Cold",
 pain="“I’ll just try one bottle first.”",
 surface="“I don’t want to commit.”",
 deep="Buying small is how she protects herself — but it is also how she under-doses, sees nothing, and quits before the product has had time to work.",
 evidence="‘She is a bundle buyer. Her natural purchase is NOT a single bottle.’ Buy 3 Get 3 was ~40% of orders. ‘The bundle is a trust signal disguised as a discount.’",
 fmt="Static offer card",
 angle="The bundle as proof of confidence, not as a discount",
 hook="If it didn’t work, we wouldn’t give you three free.",
 heading="Three bottles free is not a discount. It’s a bet.",
 subheading="We only make money if it works long enough for you to reorder.",
 idea="Directly addresses your live AOV problem — average order is now ~3 units at $60 when the 6-bottle tier used to be 40% of orders. Reframes the bundle from ‘spend more’ to ‘we’re taking the risk’, which is exactly how this distrustful buyer needs to hear it.",
 poster="Six bottles in a row, three of them clearly and honestly marked as free. Type: “If it didn’t work, we wouldn’t give you three free.” Per-bottle math in the bottom bar. No percentage anywhere on the asset.",
 reel="15–20s. 0–5s: three bottles placed down, then three more beside them. VO: “Buy three, we give you three.” 5–12s: “That’s not generosity. NMN takes about ninety days to do its work — and we only make money if you’re still here at day ninety-one.” 12–18s: the honest self-interest is the persuasion; let it sit. 18–20s: end card with per-bottle math."),

dict(n=25, persona="Linda", cat="Behavioural / purchase friction", tier="Adjacent", funnel="Retention (Day 75+)",
 pain="“I ran out and forgot to order more.”",
 surface="N/A — lapsed",
 deep="She loses the momentum she spent ninety days building, and restarting feels like admitting the first attempt failed.",
 evidence="‘The natural reorder window is 90–120 days... If you email her at Day 75, she’ll reorder. If you don’t, she’ll forget and buy from someone else.’",
 fmt="Static offer card",
 angle="Loss of momentum — never the word ‘discount’",
 hook="You’re about twelve days from running out.",
 heading="Don’t lose the ninety days you just built.",
 subheading="Reorder now and keep going without a gap.",
 idea="Use the word ‘momentum’, not ‘discount’ — momentum is precisely what she is afraid of losing. Time it to Day 75, ahead of the 90–120 day window. Retargeting and email only, never cold.",
 poster="A nearly empty bottle with four or five capsules visible, on a kitchen counter in morning light. Type: “About twelve days left.” Beneath: “Don’t lose the ninety days you just built.” Reorder CTA.",
 reel="12–15s, retargeting only. 0–4s: she tips the bottle into her palm and only a few capsules come out. 4–9s: VO: “You’re about twelve days from running out.” 9–13s: “You’ve spent ninety days building this. A gap costs you most of it.” 13–15s: one-tap reorder card. DELIVERY: Day 75 onward, purchasers only."),

# ---------------- ROBERT ----------------
dict(n=26, persona="Robert", cat="Psychological / identity", tier="Untested", funnel="Cold",
 pain="“I’m becoming my father.”",
 surface="“I’m slowing down.”",
 deep="He watched his dad lose his edge and become dependent. He refuses to let that happen to him. This is refusal, not repair.",
 evidence="‘His core insecurity: I’m becoming my father.’ Robert is reported at 1.81 ROAS — the most efficient demographic in the account.",
 fmt="Talking-head direct address",
 angle="Refusal, not repair",
 hook="You watched him slow down. You swore you wouldn’t.",
 heading="You’re not him. Not yet.",
 subheading="Your NAD+ is collapsing — that’s the edge you’re losing. Rebuild it.",
 idea="Robert is reported as the only segment above your ~1.70 breakeven and currently has zero creative written to him. His register is completely different from Linda’s: no warmth, no family softness, no glow. Plain, direct, slightly hard. VERIFY the 1.81 figure in Ads Manager before scaling against it.",
 poster="Man ~66, workshop or garage, mid-task, sleeves up, not posed. Hard side light. Plain sans type: “You watched him slow down.” Second line: “You swore you wouldn’t.” Product small, bottom-right. No lifestyle gloss, no smiling.",
 reel="20s. 0–4s: hands working — tools, a truck, a boat, something real. Male VO, flat and unsentimental: “You watched your father slow down.” 4–9s: “You told yourself that wasn’t going to be you.” 9–14s: mechanism delivered like a spec sheet — dosage, purity, what NAD+ does. Men respond to the numbers. 14–19s: him, still working, later. 19–20s: end card. No music. Male VO throughout."),

dict(n=27, persona="Robert", cat="Physiological / symptom", tier="Untested", funnel="Cold",
 pain="“I’ve lost a step and I’m the only one who’s noticed.”",
 surface="“I’m not as sharp as I was.”",
 deep="Competence is his identity. Losing sharpness threatens who he is, not just what he can do.",
 evidence="‘Motivation: recovery, cognitive sharpness, physical performance, staying active.’",
 fmt="Founder/expert explainer",
 angle="Performance decline, spec-led",
 hook="You’re a step slower and you’re the only one who’s noticed.",
 heading="You noticed before anyone else did.",
 subheading="NAD+ runs your cells’ power output. After 50 it collapses. Here’s the dosage that matters.",
 idea="Lead with data, not emotion. Robert wants a mechanism and a number — give him mg, purity and third-party testing inside the first ten seconds. This is the inverse of how you write for Linda.",
 poster="Near-clinical layout. Product on a plain surface with three specs called out in a monospace face — mg per serving, purity %, third-party tested. Almost no copy. Should read like a component datasheet, not an ad.",
 reel="20s. 0–4s: “You’re a step slower, and you’re the only one who’s noticed.” 4–12s: expert, plain, to camera, with a simple chart of NAD+ decline by decade. Numbers on screen throughout. 12–18s: dosage and testing spec. 18–20s: end card. No story, no family, no music."),

dict(n=28, persona="Robert", cat="Psychological / identity", tier="Untested", funnel="Cold",
 pain="“I won’t be a burden.”",
 surface="“I want to stay independent.”",
 deep="Dependency is his worst outcome — worse to him than illness. Needing help is the specific fear, not dying.",
 evidence="‘He watched his dad slow down, lose his edge, become dependent. He refuses to let that happen.’",
 fmt="Emotive story (restrained)",
 angle="Independence, not longevity",
 hook="You’re not afraid of getting old. You’re afraid of needing help.",
 heading="Independence is the thing worth protecting.",
 subheading="Rebuild your NAD+ while it still compounds.",
 idea="For Robert, ‘longevity’ is abstract but ‘needing help’ is visceral. Never show him being cared for — show him doing things alone, competently. The dignity of the framing is the persuasion.",
 poster="Man ~68 alone on a ladder, or under a car hood, or launching a boat — a task that requires real capability. Shot wide, no assistance in frame. Type: “You’re not afraid of getting old.” Second line: “You’re afraid of needing help.” Product bottom bar.",
 reel="20s. 0–5s: a task performed solo and well — no struggle, no comedy, no fumbling. Male VO: “It was never about living longer.” 5–11s: “It was about not having to ask.” 11–16s: mechanism, brief and factual. 16–19s: the task finished, alone. 19–20s: end card."),

dict(n=29, persona="Robert", cat="Physiological / symptom", tier="Untested", funnel="Cold",
 pain="“Recovery takes days now.”",
 surface="“I pay for it afterwards.”",
 deep="The gap between what he plans and what his body will allow. Recovery time, not performance, is how he actually measures his own aging.",
 evidence="‘Motivation: recovery, cognitive sharpness, physical performance, staying active.’ Same Sun Belt active-lifestyle geography as Linda.",
 fmt="UGC testimonial",
 angle="Recovery time as the real measure of age",
 hook="Eighteen holes used to cost you nothing.",
 heading="It’s not the round. It’s the two days after.",
 subheading="Rebuild your NAD+ and stop paying interest on a good day.",
 idea="Male mirror of row 12. Swap the activity per variant — golf, boat, garage, gym — and reuse the Sun Belt geo treatment from row 22. Cheap variant production off one master.",
 poster="A golf bag by a door, or a boat still on the trailer, late light. Nobody in frame. Type: “It’s not the round. It’s the two days after.” Product bottom bar.",
 reel="20s. 0–5s: he plays, works, moves — genuine effort. 5–10s: cut to two days of recovery, compressed — ice, the recliner, cancelled plans. Male VO, flat. 10–15s: mechanism. 15–19s: same activity the following week, no cost. 19–20s: end card."),

dict(n=30, persona="Robert", cat="Behavioural / purchase friction", tier="Untested", funnel="Warm (Day 30–45)",
 pain="“My wife started taking this and I noticed.”",
 surface="N/A — acquisition path",
 deep="He will accept a recommendation from her that he would reject from an advert. The household is a shared purchase unit.",
 evidence="Darril Morrey is the top VIP — 7 orders, $424, male-leaning name. Repeat VIPs consistently buy the mid-to-large bundle.",
 fmt="UGC testimonial",
 angle="Household expansion — sell the second bottle into the same home",
 hook="She’s been taking it for three months. You’ve noticed.",
 heading="There’s a reason she has more energy than you now.",
 subheading="Add a second bottle to her next order.",
 idea="The cheapest new customer available anywhere in the account — zero acquisition cost, existing trust, card already on file. Serve to purchasers at Day 30–45. Also lifts AOV directly, which is your single biggest revenue lever.",
 poster="Two mugs, two sets of reading glasses, one supplement bottle on a shared kitchen counter. Type: “One bottle. Two people who need it.” Add-to-order CTA.",
 reel="15s, retargeting only. 0–5s: woman ~60 to camera, amused: “I’ve been taking this for three months. He watched me for eight weeks and then started stealing them.” 5–10s: cut to him, dry: “They work.” 10–15s: “Add his to your next order.” End card. DELIVERY: existing purchasers, Day 30–45."),
]

COLUMNS = [
    ("n", "#", 5),
    ("persona", "Persona", 10),
    ("cat", "Category", 22),
    ("tier", "Evidence tier", 13),
    ("funnel", "Funnel stage", 18),
    ("pain", "Pain point", 38),
    ("surface", "Surface pain (what she says)", 30),
    ("deep", "Deep pain (what she means)", 48),
    ("evidence", "Evidence anchor", 44),
    ("fmt", "Format", 22),
    ("angle", "Angle", 40),
    ("hook", "Qualifying hook", 42),
    ("heading", "Heading", 34),
    ("subheading", "Subheading", 44),
    ("idea", "Idea", 60),
    ("poster", "Creative description (poster)", 72),
    ("reel", "Video description (reel)", 88),
]

TRACKER_COLS = ["Owner", "Status", "Asset link"]
